twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    #zamiana podstawowej templatki formularzy na bootstrap'ową
    form_themes: ['bootstrap_4_layout.html.twig']